#!/usr/bin/env python3
"""Generate a synthetic product catalog of 10000 products (5000 RU + 5000 EN)."""

import json
import random
import os

SEED = 42
TOTAL = 10000
HALF = TOTAL // 2

CATEGORIES_EN = [
    "Electronics", "Books", "Clothing", "Sports", "Home & Kitchen",
    "Beauty", "Toys", "Food", "Automotive", "Garden",
]
CATEGORIES_RU = [
    "Электроника", "Книги", "Одежда", "Спорт", "Дом и кухня",
    "Красота", "Игрушки", "Продукты", "Автотовары", "Сад и огород",
]

BRANDS_EN = [
    "ProMax", "UltraFit", "NovaTech", "ZenLine", "PeakVue",
    "CoreEdge", "VividX", "TrueGrip", "ArcStone", "BrightWave",
    "SwiftAir", "IronPulse", "ClearPath", "SkyBolt", "SnapFlex",
    "DuraLite", "EcoSmart", "CloudNine", "SteelMark", "QuickDash",
    "NexGen", "TitanX", "PrimeLine", "FlexCore", "BlueShift",
    "SonicEdge", "StarLux", "AlphaWave", "CrystalPeak", "MaverickPro",
    "ThunderBolt", "OceanBreeze", "SilverCrest", "GoldLeaf", "RedStone",
    "GreenVolt", "AquaPure", "NightOwl", "SunRise", "MoonGlow",
    "FrostByte", "BlazeTech", "WindRunner", "RockSolid", "PixelCraft",
    "VortexPro", "ZenithX", "HorizonFit", "OmegaPlus", "NovaCore",
]

BRANDS_RU = [
    "ПроМакс", "УльтраФит", "НоваТех", "ЗенЛайн", "ПикВью",
    "КорЭдж", "ВивидИкс", "ТруГрип", "АркСтоун", "БрайтВейв",
    "СвифтЭйр", "АйронПульс", "КлирПат", "СкайБолт", "СнапФлекс",
    "ДюраЛайт", "ЭкоСмарт", "КлаудНайн", "СтилМарк", "КвикДэш",
    "НексГен", "ТитанИкс", "ПраймЛайн", "ФлексКор", "БлюШифт",
    "СоникЭдж", "СтарЛюкс", "АльфаВейв", "КристалПик", "МаверикПро",
    "ТандерБолт", "ОкеанБриз", "СильверКрест", "ГолдЛиф", "РедСтоун",
    "ГринВольт", "АкваПьюр", "НайтОул", "СанРайз", "МунГлоу",
    "ФростБайт", "БлейзТех", "ВиндРанер", "РокСолид", "ПикселКрафт",
    "ВортексПро", "ЗенитИкс", "ГоризонтФит", "ОмегаПлюс", "НоваКор",
]

BOOK_TOPICS_EN = [
    "Machine Learning", "Modern Cooking", "Personal Finance",
    "Digital Photography", "Urban Gardening", "Mindfulness",
    "World History", "Data Science", "Creative Writing",
    "Behavioral Economics", "Astronomy", "Chess Strategy",
    "Graphic Design", "Public Speaking", "Game Theory",
    "Quantum Physics", "Marine Biology", "Jazz Music",
    "Ancient Philosophy", "Nutrition Science", "Film Making",
    "Sustainable Living", "Robotics", "Cryptography",
    "Neuroscience", "Poetry", "Entrepreneurship",
    "Architecture", "Psychology", "Linguistics",
]

BOOK_TOPICS_RU = [
    "машинного обучения", "современной кулинарии", "личных финансов",
    "цифровой фотографии", "городского садоводства", "осознанности",
    "мировой истории", "анализа данных", "креативного письма",
    "поведенческой экономики", "астрономии", "шахматной стратегии",
    "графического дизайна", "ораторского искусства", "теории игр",
    "квантовой физики", "морской биологии", "джазовой музыки",
    "античной философии", "нутрициологии", "кинематографии",
    "экологичного образа жизни", "робототехники", "криптографии",
    "нейронауки", "поэзии", "предпринимательства",
    "архитектуры", "психологии", "лингвистики",
]

NAMES_EN = {
    "Electronics": [
        "Wireless Earbuds {}", "Bluetooth Speaker {}", "Smart Watch {}",
        "USB-C Hub {}", "Portable Charger {}", "4K Webcam {}",
        "Noise-Cancelling Headphones {}", "Mechanical Keyboard {}",
        "Wireless Mouse {}", "LED Monitor {} 27\"",
        "Tablet Stand {}", "HDMI Cable {} 2m",
        "Smart Plug {}", "Action Camera {}",
        "Portable SSD {} 1TB", "Gaming Headset {}",
        "Wireless Charger Pad {}", "USB Microphone {}",
        "Smart Doorbell {}", "Dash Cam {} 4K",
        "Fitness Tracker {}", "E-Reader {} 7\"",
        "Portable Projector {}", "Wi-Fi Extender {}",
        "Smart LED Strip {}", "Drone {} Mini",
        "VR Headset {}", "Power Strip {} Smart",
        "Digital Thermometer {}", "Smart Scale {}",
    ],
    "Books": [
        "\"The Art of {}\"", "\"Mastering {}\"", "\"Introduction to {}\"",
        "\"{}: A Complete Guide\"", "\"The {} Handbook\"",
        "\"Practical {}\"", "\"{} for Beginners\"",
        "\"Advanced {} Techniques\"", "\"The {} Revolution\"",
        "\"{} Essentials\"", "\"The {} Masterclass\"",
        "\"{}: From Zero to Hero\"", "\"Exploring {}\"",
        "\"The Science of {}\"", "\"{}: Theory and Practice\"",
        "\"Understanding {}\"", "\"The {} Playbook\"",
        "\"{}: A Modern Approach\"", "\"Rethinking {}\"",
        "\"The Future of {}\"",
    ],
    "Clothing": [
        "{} Cotton T-Shirt", "{} Slim Fit Jeans", "{} Waterproof Jacket",
        "{} Running Shoes", "{} Wool Sweater", "{} Leather Belt",
        "{} Casual Hoodie", "{} Linen Shirt", "{} Down Vest",
        "{} Merino Socks Pack", "{} Denim Jacket", "{} Cargo Pants",
        "{} Fleece Pullover", "{} Rain Poncho", "{} Thermal Leggings",
        "{} Canvas Sneakers", "{} Parka Coat", "{} Polo Shirt",
        "{} Hiking Boots", "{} Silk Scarf", "{} Beanie Hat",
        "{} Swim Trunks", "{} Compression Shorts", "{} Flannel Shirt",
        "{} Oxford Shoes", "{} Windbreaker", "{} Chino Pants",
        "{} V-Neck Sweater", "{} Sports Bra", "{} Leather Gloves",
    ],
    "Sports": [
        "{} Yoga Mat", "{} Resistance Bands Set", "{} Adjustable Dumbbells",
        "{} Jump Rope", "{} Foam Roller", "{} Running Armband",
        "{} Cycling Gloves", "{} Swim Goggles", "{} Tennis Racket",
        "{} Hiking Backpack 40L", "{} Boxing Gloves", "{} Ab Roller",
        "{} Pull-Up Bar", "{} Kettlebell 16kg", "{} Speed Ladder",
        "{} Gym Bag", "{} Wrist Wraps", "{} Climbing Harness",
        "{} Badminton Set", "{} Skateboard", "{} Soccer Ball",
        "{} Basketball", "{} Punching Bag", "{} Rowing Machine Strap",
        "{} Ski Goggles", "{} Ice Skates", "{} Surfboard Wax",
        "{} Golf Tees Pack", "{} Fishing Rod", "{} Camping Tent 2P",
    ],
    "Home & Kitchen": [
        "{} Stainless Steel Cookware Set", "{} Blender", "{} Air Fryer",
        "{} Coffee Grinder", "{} Knife Set", "{} Cutting Board",
        "{} Food Storage Containers", "{} Cast Iron Skillet",
        "{} Electric Kettle", "{} Silicone Baking Mat",
        "{} Toaster Oven", "{} Pressure Cooker", "{} Spice Rack",
        "{} Wine Opener Set", "{} Dish Drying Rack", "{} Mixing Bowls Set",
        "{} Bread Box", "{} Ice Cream Maker", "{} Waffle Iron",
        "{} Salad Spinner", "{} Measuring Cups Set", "{} Rolling Pin",
        "{} Apron Set", "{} Timer Digital", "{} Herb Garden Kit",
        "{} Vacuum Sealer", "{} Mandoline Slicer", "{} Mortar and Pestle",
        "{} Dutch Oven", "{} French Press",
    ],
    "Beauty": [
        "{} Vitamin C Serum", "{} Moisturizing Cream", "{} Hair Dryer",
        "{} Makeup Brush Set", "{} Perfume 50ml", "{} Facial Cleanser",
        "{} Lip Balm Set", "{} Eye Cream", "{} Sunscreen SPF 50",
        "{} Body Lotion", "{} Hair Straightener", "{} Nail Polish Set",
        "{} Face Mask Pack", "{} Shampoo Bar", "{} Beard Oil",
        "{} Makeup Mirror LED", "{} Eyelash Curler", "{} Body Scrub",
        "{} Hand Cream Trio", "{} Aromatherapy Diffuser",
        "{} Detangling Brush", "{} BB Cream", "{} Setting Spray",
        "{} Lip Gloss Set", "{} Hair Serum", "{} Foot Cream",
        "{} Micellar Water", "{} Brow Pencil", "{} Concealer Palette",
        "{} Bath Bomb Set",
    ],
    "Toys": [
        "{} Building Blocks 500pc", "{} Remote Control Car",
        "{} Puzzle 1000pc", "{} Plush Bear", "{} Board Game",
        "{} Science Kit", "{} Magnetic Tiles Set",
        "{} Dollhouse", "{} Toy Train Set", "{} Art Supplies Kit",
        "{} Dinosaur Figures Set", "{} Play Kitchen Set",
        "{} Water Gun", "{} Marble Run", "{} Telescope for Kids",
        "{} Card Game", "{} Slime Kit", "{} Toy Robot",
        "{} Magic Set", "{} Drum Set Kids", "{} Play-Doh Set",
        "{} Toy Soldiers Set", "{} Sticker Book 500pc",
        "{} Walkie Talkie Pair", "{} Microscope Kids",
        "{} Finger Puppets Set", "{} Foam Airplane",
        "{} Beach Toy Set", "{} Toy Tool Bench", "{} Baby Rattle Set",
    ],
    "Food": [
        "{} Organic Honey 500g", "{} Dark Chocolate 85%",
        "{} Green Tea 100 bags", "{} Mixed Nuts 1kg",
        "{} Extra Virgin Olive Oil 750ml", "{} Protein Bars Pack",
        "{} Dried Mango Slices", "{} Peanut Butter 500g",
        "{} Instant Oatmeal 12pk", "{} Coconut Water 6pk",
        "{} Quinoa 1kg", "{} Granola Mix 750g",
        "{} Matcha Powder 100g", "{} Chia Seeds 500g",
        "{} Almond Milk 6pk", "{} Energy Gel Pack",
        "{} Beef Jerky 200g", "{} Dried Cranberries 300g",
        "{} Rice Crackers Pack", "{} Maple Syrup 500ml",
        "{} Soy Sauce 250ml", "{} Hot Sauce Set",
        "{} Trail Mix 1kg", "{} Coconut Oil 500ml",
        "{} Apple Cider Vinegar 750ml", "{} Popcorn Kernels 1kg",
        "{} Herbal Tea Collection", "{} Espresso Capsules 50pk",
        "{} Sparkling Water 12pk", "{} Dried Apricots 500g",
    ],
    "Automotive": [
        "{} Car Phone Mount", "{} Dash Cam 1080p", "{} Tire Inflator",
        "{} Car Vacuum Cleaner", "{} LED Headlight Bulbs",
        "{} Seat Cushion", "{} Windshield Sunshade",
        "{} Trunk Organizer", "{} Car Charger Dual USB",
        "{} Steering Wheel Cover", "{} Jump Starter Pack",
        "{} Tire Pressure Gauge", "{} Car Floor Mats Set",
        "{} Roof Rack Cross Bars", "{} Car Wax Kit",
        "{} OBD2 Scanner", "{} Backup Camera", "{} Air Freshener Set",
        "{} Emergency Kit", "{} Car Cover Waterproof",
        "{} Phone Holder Vent Mount", "{} Blind Spot Mirrors",
        "{} Cargo Net", "{} Ice Scraper", "{} Battery Charger",
        "{} Paint Repair Pen", "{} Wheel Brush Set",
        "{} Door Edge Guards", "{} GPS Tracker", "{} Cabin Air Filter",
    ],
    "Garden": [
        "{} Garden Hose 30m", "{} Pruning Shears", "{} Raised Garden Bed",
        "{} Solar Path Lights 8pk", "{} Compost Bin",
        "{} Lawn Sprinkler", "{} Hand Trowel Set",
        "{} Plant Pots Set 6pc", "{} Leaf Blower",
        "{} Garden Kneeler", "{} Wheelbarrow", "{} Hedge Trimmer",
        "{} Bird Feeder", "{} Rain Gauge", "{} Potting Soil 25L",
        "{} Garden Fence Panel", "{} Outdoor Thermometer",
        "{} Lawn Seed 5kg", "{} Weed Barrier Fabric",
        "{} Drip Irrigation Kit", "{} Greenhouse Mini",
        "{} Garden Torch Set", "{} Plant Labels 50pk",
        "{} Flower Bulbs Mix", "{} Mulch Mat",
        "{} Soil pH Meter", "{} Bug Zapper", "{} Garden Arch",
        "{} Hanging Basket Set", "{} Outdoor Timer",
    ],
}

NAMES_RU = {
    "Электроника": [
        "Беспроводные наушники {}", "Bluetooth-колонка {}", "Смарт-часы {}",
        "USB-C хаб {}", "Портативный аккумулятор {}", "Веб-камера 4K {}",
        "Наушники с шумоподавлением {}", "Механическая клавиатура {}",
        "Беспроводная мышь {}", "LED-монитор {} 27\"",
        "Подставка для планшета {}", "Кабель HDMI {} 2м",
        "Умная розетка {}", "Экшн-камера {}",
        "Портативный SSD {} 1ТБ", "Игровая гарнитура {}",
        "Беспроводная зарядка {}", "USB-микрофон {}",
        "Умный звонок {}", "Видеорегистратор {} 4K",
        "Фитнес-трекер {}", "Электронная книга {} 7\"",
        "Портативный проектор {}", "Wi-Fi усилитель {}",
        "Умная LED-лента {}", "Мини-дрон {}",
        "VR-шлем {}", "Умный удлинитель {}",
        "Цифровой термометр {}", "Умные весы {}",
    ],
    "Книги": [
        "\"Искусство {}\"", "\"Мастерство {}\"", "\"Введение в {}\"",
        "\"{}: полное руководство\"", "\"Справочник по {}\"",
        "\"Практический {}\"", "\"{} для начинающих\"",
        "\"Продвинутые техники {}\"", "\"Революция {}\"",
        "\"Основы {}\"", "\"Мастер-класс по {}\"",
        "\"{}: от нуля до профи\"", "\"Исследуя {}\"",
        "\"Наука {}\"", "\"{}: теория и практика\"",
        "\"Понимание {}\"", "\"Стратегия {}\"",
        "\"{}: современный подход\"", "\"Переосмысляя {}\"",
        "\"Будущее {}\"",
    ],
    "Одежда": [
        "{} хлопковая футболка", "{} джинсы слим-фит", "{} непромокаемая куртка",
        "{} беговые кроссовки", "{} шерстяной свитер", "{} кожаный ремень",
        "{} повседневное худи", "{} льняная рубашка", "{} пуховый жилет",
        "{} набор носков из мериноса", "{} джинсовая куртка", "{} брюки карго",
        "{} флисовый пуловер", "{} дождевик-пончо", "{} термолеггинсы",
        "{} парусиновые кеды", "{} парка", "{} поло",
        "{} треккинговые ботинки", "{} шёлковый шарф", "{} шапка бини",
        "{} плавки", "{} компрессионные шорты", "{} фланелевая рубашка",
        "{} оксфордские туфли", "{} ветровка", "{} брюки чинос",
        "{} свитер с V-вырезом", "{} спортивный топ", "{} кожаные перчатки",
    ],
    "Спорт": [
        "{} коврик для йоги", "{} набор эспандеров", "{} разборные гантели",
        "{} скакалка", "{} массажный ролик", "{} спортивный чехол на руку",
        "{} велосипедные перчатки", "{} очки для плавания", "{} теннисная ракетка",
        "{} туристический рюкзак 40л", "{} боксёрские перчатки", "{} ролик для пресса",
        "{} турник в дверной проём", "{} гиря 16кг", "{} координационная лестница",
        "{} спортивная сумка", "{} кистевые бинты", "{} скалолазная обвязка",
        "{} набор для бадминтона", "{} скейтборд", "{} футбольный мяч",
        "{} баскетбольный мяч", "{} боксёрская груша", "{} ремни для гребного тренажёра",
        "{} горнолыжные очки", "{} коньки", "{} воск для сёрфборда",
        "{} набор тиз для гольфа", "{} удочка", "{} палатка 2-местная",
    ],
    "Дом и кухня": [
        "{} набор посуды из нержавейки", "{} блендер", "{} аэрогриль",
        "{} кофемолка", "{} набор ножей", "{} разделочная доска",
        "{} контейнеры для хранения", "{} чугунная сковорода",
        "{} электрический чайник", "{} силиконовый коврик для выпечки",
        "{} мини-печь", "{} мультиварка", "{} подставка для специй",
        "{} набор для вина", "{} сушилка для посуды", "{} набор мисок",
        "{} хлебница", "{} мороженица", "{} вафельница",
        "{} центрифуга для салата", "{} набор мерных стаканов", "{} скалка",
        "{} набор фартуков", "{} цифровой таймер", "{} набор для выращивания трав",
        "{} вакууматор", "{} овощерезка-мандолина", "{} ступка с пестиком",
        "{} жаровня", "{} френч-пресс",
    ],
    "Красота": [
        "{} сыворотка с витамином C", "{} увлажняющий крем", "{} фен для волос",
        "{} набор кистей для макияжа", "{} парфюм 50мл", "{} гель для умывания",
        "{} набор бальзамов для губ", "{} крем для век", "{} солнцезащитный крем SPF 50",
        "{} лосьон для тела", "{} выпрямитель для волос", "{} набор лаков для ногтей",
        "{} набор масок для лица", "{} твёрдый шампунь", "{} масло для бороды",
        "{} зеркало с LED-подсветкой", "{} щипцы для ресниц", "{} скраб для тела",
        "{} набор кремов для рук", "{} аромадиффузор",
        "{} расчёска-распутыватель", "{} BB-крем", "{} фиксирующий спрей",
        "{} набор блесков для губ", "{} сыворотка для волос", "{} крем для ног",
        "{} мицеллярная вода", "{} карандаш для бровей", "{} палетка консилеров",
        "{} набор бомбочек для ванны",
    ],
    "Игрушки": [
        "{} конструктор 500 дет.", "{} радиоуправляемая машинка",
        "{} пазл 1000 дет.", "{} плюшевый мишка", "{} настольная игра",
        "{} научный набор", "{} магнитный конструктор",
        "{} кукольный домик", "{} железная дорога", "{} набор для творчества",
        "{} набор фигурок динозавров", "{} игровая кухня",
        "{} водяной пистолет", "{} лабиринт с шариками", "{} детский телескоп",
        "{} карточная игра", "{} набор для слаймов", "{} робот-игрушка",
        "{} набор фокусника", "{} детская барабанная установка", "{} набор пластилина",
        "{} набор солдатиков", "{} книга наклеек 500шт",
        "{} пара раций", "{} детский микроскоп",
        "{} набор пальчиковых кукол", "{} самолёт из пенопласта",
        "{} набор пляжных игрушек", "{} игрушечная мастерская", "{} набор погремушек",
    ],
    "Продукты": [
        "{} органический мёд 500г", "{} тёмный шоколад 85%",
        "{} зелёный чай 100 пакетиков", "{} ореховая смесь 1кг",
        "{} оливковое масло Extra Virgin 750мл", "{} протеиновые батончики",
        "{} сушёное манго", "{} арахисовая паста 500г",
        "{} овсяная каша 12шт", "{} кокосовая вода 6шт",
        "{} киноа 1кг", "{} гранола микс 750г",
        "{} матча 100г", "{} семена чиа 500г",
        "{} миндальное молоко 6шт", "{} энергетический гель",
        "{} вяленая говядина 200г", "{} сушёная клюква 300г",
        "{} рисовые хлебцы", "{} кленовый сироп 500мл",
        "{} соевый соус 250мл", "{} набор острых соусов",
        "{} трейл микс 1кг", "{} кокосовое масло 500мл",
        "{} яблочный уксус 750мл", "{} зёрна для попкорна 1кг",
        "{} коллекция травяных чаёв", "{} капсулы эспрессо 50шт",
        "{} газированная вода 12шт", "{} курага 500г",
    ],
    "Автотовары": [
        "{} автомобильный держатель", "{} видеорегистратор 1080p", "{} компрессор для шин",
        "{} автопылесос", "{} LED-лампы для фар",
        "{} подушка на сиденье", "{} солнцезащитная шторка",
        "{} органайзер в багажник", "{} автозарядка Dual USB",
        "{} оплётка на руль", "{} пусковое устройство",
        "{} манометр для шин", "{} набор автоковриков",
        "{} поперечины на крышу", "{} набор для полировки",
        "{} OBD2 сканер", "{} камера заднего вида", "{} набор ароматизаторов",
        "{} аварийный набор", "{} чехол-тент водонепроницаемый",
        "{} держатель на вентиляцию", "{} зеркала слепых зон",
        "{} сетка в багажник", "{} скребок для льда", "{} зарядка для АКБ",
        "{} карандаш для сколов", "{} набор щёток для колёс",
        "{} защита кромки двери", "{} GPS-трекер", "{} салонный фильтр",
    ],
    "Сад и огород": [
        "{} садовый шланг 30м", "{} секатор", "{} высокая грядка",
        "{} солнечные фонари 8шт", "{} компостный ящик",
        "{} разбрызгиватель для газона", "{} набор садовых лопаток",
        "{} набор горшков 6шт", "{} садовый пылесос",
        "{} подставка под колени", "{} садовая тачка", "{} кусторез",
        "{} кормушка для птиц", "{} дождемер", "{} грунт 25л",
        "{} панель садового забора", "{} уличный термометр",
        "{} семена газона 5кг", "{} агроткань от сорняков",
        "{} капельный полив", "{} мини-теплица",
        "{} набор садовых факелов", "{} таблички для растений 50шт",
        "{} микс луковиц цветов", "{} мульча-мат",
        "{} pH-метр для почвы", "{} уничтожитель насекомых", "{} садовая арка",
        "{} набор подвесных кашпо", "{} уличный таймер полива",
    ],
}

DESCS_EN = {
    "Electronics": [
        "High-performance device with advanced connectivity features and long battery life. Perfect for everyday use at home or on the go.",
        "Compact and lightweight design with premium build quality. Features fast charging and seamless wireless pairing with all major devices.",
        "Engineered for productivity and entertainment. Supports multiple device connections and delivers crystal-clear audio and video quality.",
        "Next-generation technology packed into a sleek, portable form factor. Ideal for professionals and tech enthusiasts who demand reliability.",
        "Energy-efficient device with intuitive controls and universal compatibility. Built to last with durable materials and backed by a 2-year warranty.",
        "Cutting-edge features in a minimalist design. Delivers outstanding performance for streaming, gaming, and everyday multitasking.",
        "Ultra-responsive device with low-latency connectivity. Precision-engineered components ensure consistent, reliable operation over years of use.",
        "Smart device with app integration and voice assistant support. Automates your daily routines and keeps you connected effortlessly.",
        "Ruggedized build with IP67 water and dust resistance. Works flawlessly in harsh conditions, from workshops to outdoor adventures.",
        "Premium audio-visual experience with studio-quality drivers and high-resolution display. A step up for content creators and audiophiles alike.",
    ],
    "Books": [
        "A comprehensive and accessible guide that takes you from fundamentals to advanced topics. Packed with practical examples and exercises.",
        "Written by industry experts, this book offers deep insights and actionable strategies. Essential reading for anyone looking to expand their knowledge.",
        "Engaging narrative combined with rigorous research. Each chapter builds on the last, making complex ideas easy to understand and apply.",
        "A bestselling reference that covers both theory and practice. Includes case studies, diagrams, and a detailed glossary for quick reference.",
        "Whether you are a complete beginner or an experienced practitioner, this book provides fresh perspectives and proven techniques to take your skills to the next level.",
        "A thought-provoking exploration that challenges conventional thinking. Draws on real-world examples from dozens of industries and disciplines.",
        "Concise, well-structured chapters make this the perfect desk reference. Updated edition includes the latest research and industry trends.",
        "An inspiring journey through the subject that blends storytelling with data-driven analysis. Readers call it 'the book they wish they had years ago.'",
        "Step-by-step walkthroughs and downloadable resources make hands-on learning easy. Ideal companion for self-study and classroom use.",
        "Critically acclaimed and translated into 15 languages. A foundational text that has shaped how professionals worldwide approach the topic.",
    ],
    "Clothing": [
        "Made from premium natural fabrics for exceptional comfort and breathability. Machine washable and designed to hold its shape after repeated wear.",
        "Stylish and versatile piece suitable for casual and semi-formal occasions. Features reinforced stitching and a modern, flattering fit.",
        "Lightweight yet durable construction with moisture-wicking properties. Ideal for active lifestyles, travel, and everyday wear in any season.",
        "Crafted with attention to detail using sustainably sourced materials. The ergonomic cut ensures freedom of movement without compromising style.",
        "Classic design updated with contemporary touches. Fade-resistant colors and pre-shrunk fabric guarantee long-lasting quality and appearance.",
        "Four-way stretch fabric moves with you during any activity. Quick-dry technology keeps you cool and comfortable from morning to night.",
        "Insulated with responsibly sourced down for warmth without bulk. Packable design compresses into its own pocket for easy travel.",
        "Premium leather craftsmanship with hand-finished edges. Develops a rich patina over time, making each piece uniquely yours.",
        "Relaxed fit with hidden pockets and reinforced seams for everyday durability. Garment-dyed for a soft, lived-in look from day one.",
        "Reflective accents and high-visibility panels for safe low-light outings. Windproof and water-repellent shell protects against the elements.",
    ],
    "Sports": [
        "Professional-grade equipment designed for athletes of all levels. Durable construction ensures reliable performance through intense training sessions.",
        "Ergonomic design with non-slip grip for safe and effective workouts. Lightweight and portable, perfect for home gyms and outdoor training.",
        "Engineered for maximum performance and comfort during exercise. High-quality materials provide excellent support and long-term durability.",
        "Versatile fitness accessory suitable for strength training, cardio, and flexibility work. Comes with a carrying case and a quick-start guide.",
        "Tested by professional athletes and fitness coaches. Compact design saves space while delivering gym-quality results in any environment.",
        "Competition-ready gear that meets international standards. Reinforced construction handles even the most punishing training regimens.",
        "Adjustable settings let you customize resistance and intensity as your fitness level grows. Great for progressive overload training.",
        "Breathable, moisture-wicking materials keep you dry during high-intensity intervals. Secure fit stays in place through dynamic movements.",
        "All-weather design for outdoor training year-round. UV-resistant, quick-dry surface cleans with a simple wipe-down after each session.",
        "Includes an illustrated workout guide and a QR code linking to free training videos. Perfect for beginners building a home gym.",
    ],
    "Home & Kitchen": [
        "Premium kitchen essential made from food-grade, BPA-free materials. Dishwasher safe and designed for effortless daily cooking and meal preparation.",
        "Durable construction with an elegant finish that complements any kitchen decor. Heat-resistant and easy to clean for hassle-free maintenance.",
        "Multi-functional kitchen tool that saves time and counter space. Features intuitive controls and consistent results for both beginners and seasoned cooks.",
        "Crafted from restaurant-quality materials for exceptional heat distribution and longevity. A must-have for anyone passionate about home cooking.",
        "Space-saving design with generous capacity for family-sized portions. Energy-efficient operation helps reduce electricity bills without sacrificing performance.",
        "Non-stick ceramic coating for healthy, oil-free cooking. Oven-safe up to 260 °C and compatible with all stovetop types including induction.",
        "Airtight seal locks in freshness for up to five times longer than standard containers. Stackable design keeps your pantry organized.",
        "Double-wall vacuum insulation maintains your drink temperature for hours. Leak-proof lid and one-hand operation make it ideal for commuters.",
        "Precision temperature control with a digital display for repeatable results. Quiet motor won't disturb early-morning or late-night cooking.",
        "Handcrafted from sustainably harvested bamboo with food-safe mineral oil finish. Naturally antimicrobial and gentle on knife edges.",
    ],
    "Beauty": [
        "Dermatologist-tested formula with natural ingredients for gentle, effective skincare. Suitable for all skin types including sensitive skin.",
        "Luxurious product that nourishes and revitalizes your skin with clinically proven active ingredients. Visible results within two weeks of regular use.",
        "Professional-quality beauty tool for salon-grade results at home. Lightweight, ergonomic design reduces hand fatigue during extended use.",
        "Cruelty-free and paraben-free formula enriched with vitamins and antioxidants. Absorbs quickly without leaving a greasy residue.",
        "Innovative skincare solution backed by scientific research. Hydrates, protects, and restores your skin's natural glow throughout the day.",
        "Vegan formula with sustainably harvested botanical extracts. Glass packaging is fully recyclable, supporting your eco-conscious lifestyle.",
        "Salon-tested heat protection up to 230 °C. Ionic technology reduces frizz and adds mirror-like shine in a single pass.",
        "Buildable coverage that feels weightless on skin. Infused with hyaluronic acid to keep your complexion hydrated under makeup all day.",
        "Overnight repair complex with retinol and peptides. Wake up to visibly firmer, smoother skin after just one night's application.",
        "Long-wear formula stays vibrant for up to 12 hours without touch-ups. Transfer-proof and kiss-proof for confident, all-day color.",
    ],
    "Toys": [
        "Educational and entertaining toy that sparks creativity and develops problem-solving skills. Made from non-toxic, child-safe materials.",
        "Hours of imaginative play for children ages 3 and up. Bright colors and sturdy construction withstand enthusiastic play sessions.",
        "Award-winning toy that encourages STEM learning through hands-on experimentation. Includes detailed instructions and fun project ideas.",
        "Interactive playset that grows with your child, offering multiple difficulty levels. Promotes fine motor skills, spatial awareness, and teamwork.",
        "Classic toy reimagined with modern safety features and vibrant designs. Makes an excellent birthday or holiday gift for curious young minds.",
        "Screen-free entertainment that keeps kids engaged for hours. Develops patience, strategy, and social skills through cooperative gameplay.",
        "Eco-friendly toy made from recycled ocean-bound plastic. Durable enough for indoor and outdoor play while teaching kids about sustainability.",
        "Expandable system compatible with major building-block brands. Start small and grow your collection with themed expansion packs.",
        "Realistic sound effects and lights bring the adventure to life. Requires 2 AA batteries (included). Recommended for ages 5–12.",
        "Parent-approved and independently safety-certified. Rounded edges, lead-free paint, and machine-washable fabric for worry-free play.",
    ],
    "Food": [
        "Premium quality product sourced from certified organic farms. Rich in natural nutrients with no artificial preservatives, colors, or flavors.",
        "Delicious and nutritious snack perfect for on-the-go energy. Sealed in resealable packaging to maintain freshness after every use.",
        "Carefully selected ingredients processed under strict quality controls. Great source of protein and fiber for a balanced, healthy diet.",
        "Artisanal product with a distinctive, full-bodied flavor profile. Ideal for cooking, baking, or enjoying straight out of the package.",
        "Sustainably produced with eco-friendly packaging. Low in sugar and rich in essential vitamins and minerals for the whole family.",
        "Small-batch roasted for maximum aroma and depth of flavor. Single-origin beans traceable to the farm where they were grown.",
        "Gluten-free and non-GMO verified. Perfect for allergy-conscious households without compromising on taste or texture.",
        "Cold-pressed and unrefined to preserve all natural enzymes and nutrients. Versatile kitchen staple for dressings, marinades, and baking.",
        "High-protein, low-carb snack ideal for keto and paleo diets. No added sugar, no artificial sweeteners — just real, clean ingredients.",
        "Family-size pack with individually wrapped portions for lunchboxes and travel. Kids and adults love the balanced sweet-and-savory taste.",
    ],
    "Automotive": [
        "Universal-fit car accessory compatible with most vehicle makes and models. Easy tool-free installation takes less than five minutes.",
        "Durable automotive product built to withstand extreme temperatures and daily wear. Improves driving comfort and vehicle organization.",
        "Safety-focused car accessory with reliable performance in all weather conditions. Compact design fits neatly without blocking visibility.",
        "High-quality automotive accessory made from premium materials for long-lasting use. Enhances your driving experience and keeps your car tidy.",
        "Plug-and-play device with smart features for modern vehicles. Energy-efficient operation with overcharge and short-circuit protection built in.",
        "Military-grade construction tested to survive drops, vibrations, and temperature swings. Ideal for trucks, SUVs, and off-road vehicles.",
        "OEM-quality replacement that matches factory specifications. Restores performance and passes state inspection requirements with no modifications.",
        "360-degree rotation mount with one-touch release mechanism. Shock-absorbing pad protects your phone from road vibrations on any surface.",
        "Ultra-bright LED output with a 50,000-hour lifespan. Instant-on, no warm-up time, and a focused beam pattern that won't blind oncoming traffic.",
        "Eco-leather finish with memory-foam cushioning for long-haul comfort. Fits most front and rear seats and installs without tools.",
    ],
    "Garden": [
        "Heavy-duty garden tool designed for professional landscapers and home gardeners alike. Rust-resistant construction ensures seasons of reliable use.",
        "Eco-friendly gardening solution that promotes healthy soil and vigorous plant growth. Easy to assemble with no special tools required.",
        "Weather-resistant outdoor product built to handle sun, rain, and frost. Attractive design adds a decorative touch to any yard or patio.",
        "Ergonomic garden tool that reduces hand and back strain during extended gardening sessions. Lightweight yet strong enough for tough garden tasks.",
        "Complete gardening kit with everything you need to start planting right away. Ideal for raised beds, container gardens, and landscaping projects.",
        "Self-watering mechanism keeps plants hydrated for up to two weeks. Great for vacations or busy schedules when you can't water daily.",
        "Galvanized steel frame withstands years of outdoor exposure without rust or corrosion. Quick-connect fittings make seasonal setup a breeze.",
        "Solar-powered with an automatic dusk-to-dawn sensor. No wiring needed — simply stake into the ground and enjoy warm ambient light.",
        "Expandable modular design lets you customize the layout to fit any garden shape. Easy to rearrange as your planting plan evolves.",
        "USDA-approved organic formulation safe for edible gardens. Encourages beneficial microorganisms while suppressing common garden pests naturally.",
    ],
}

DESCS_RU = {
    "Электроника": [
        "Высокопроизводительное устройство с продвинутыми функциями подключения и длительным временем работы от батареи. Подходит для повседневного использования дома и в поездках.",
        "Компактный и лёгкий дизайн с премиальным качеством сборки. Поддерживает быструю зарядку и бесшовное беспроводное сопряжение со всеми основными устройствами.",
        "Разработано для продуктивной работы и развлечений. Поддерживает подключение нескольких устройств, обеспечивая кристально чистый звук и изображение.",
        "Технологии нового поколения в стильном портативном корпусе. Идеально для профессионалов и энтузиастов, которым важна надёжность.",
        "Энергоэффективное устройство с интуитивным управлением и универсальной совместимостью. Прочные материалы и гарантия 2 года.",
        "Передовые функции в минималистичном дизайне. Превосходная производительность для стриминга, игр и повседневных задач.",
        "Сверхчувствительное устройство с низкой задержкой сигнала. Прецизионные компоненты обеспечивают стабильную работу на протяжении многих лет.",
        "Умное устройство с интеграцией приложений и поддержкой голосового ассистента. Автоматизирует повседневные задачи и поддерживает вашу связь с миром.",
        "Усиленный корпус с защитой IP67 от воды и пыли. Безупречно работает в суровых условиях — от мастерской до похода.",
        "Премиальный аудиовизуальный опыт со студийными драйверами и дисплеем высокого разрешения. Выбор контент-мейкеров и аудиофилов.",
    ],
    "Книги": [
        "Исчерпывающее и доступное руководство, которое проведёт вас от основ до продвинутых тем. Множество практических примеров и упражнений.",
        "Написана экспертами отрасли, книга предлагает глубокий анализ и действенные стратегии. Обязательное чтение для всех, кто хочет расширить свои знания.",
        "Увлекательное повествование в сочетании с тщательным исследованием. Каждая глава развивает предыдущую, делая сложные идеи понятными и применимыми.",
        "Бестселлер, охватывающий теорию и практику. Включает разборы кейсов, схемы и подробный глоссарий для быстрого ориентирования.",
        "Подходит как новичкам, так и опытным специалистам. Книга предлагает свежие перспективы и проверенные методики для роста профессиональных навыков.",
        "Провокационное исследование, бросающее вызов устоявшимся представлениям. Опирается на примеры из десятков отраслей и дисциплин.",
        "Лаконичные, хорошо структурированные главы делают книгу идеальным настольным справочником. Обновлённое издание включает последние исследования и тренды.",
        "Вдохновляющее путешествие по теме, сочетающее сторителлинг с аналитикой на основе данных. Читатели называют её «книгой, которую хотели бы иметь много лет назад».",
        "Пошаговые разборы и загружаемые ресурсы упрощают практическое обучение. Идеальный компаньон для самоподготовки и учебных занятий.",
        "Признанная критиками и переведённая на 15 языков. Фундаментальный труд, изменивший подход профессионалов во всём мире к данной теме.",
    ],
    "Одежда": [
        "Изготовлена из натуральных тканей премиум-качества для исключительного комфорта и воздухопроницаемости. Можно стирать в машинке, сохраняет форму после многократных стирок.",
        "Стильная и универсальная вещь, подходящая для повседневных и полуформальных случаев. Усиленные швы и современный крой.",
        "Лёгкая, но прочная конструкция с влагоотводящими свойствами. Идеальна для активного образа жизни, путешествий и повседневной носки в любой сезон.",
        "Выполнена с вниманием к деталям из экологичных материалов. Эргономичный крой обеспечивает свободу движений без ущерба для стиля.",
        "Классический дизайн с современными акцентами. Устойчивые к выцветанию цвета и усадкостойкая ткань гарантируют долговечность.",
        "Ткань с четырёхсторонней эластичностью двигается вместе с вами. Технология быстрого высыхания сохраняет комфорт с утра до вечера.",
        "Утеплена ответственно добытым пухом для тепла без объёма. Упаковывается в собственный карман для удобства в поездках.",
        "Премиальная кожа ручной работы с отделкой краёв. Со временем приобретает благородную патину, делая каждое изделие уникальным.",
        "Свободный крой со скрытыми карманами и усиленными швами для повседневной прочности. Окрашивание по готовому изделию для мягкого винтажного вида.",
        "Светоотражающие элементы и панели повышенной видимости для безопасных прогулок при слабом освещении. Ветрозащитная и водоотталкивающая оболочка.",
    ],
    "Спорт": [
        "Профессиональное оборудование для спортсменов любого уровня подготовки. Прочная конструкция обеспечивает надёжную работу во время интенсивных тренировок.",
        "Эргономичный дизайн с нескользящей поверхностью для безопасных и эффективных тренировок. Лёгкий и портативный, отлично подходит для домашних и уличных занятий.",
        "Разработан для максимальной производительности и комфорта во время упражнений. Качественные материалы обеспечивают отличную поддержку и долговечность.",
        "Универсальный фитнес-аксессуар для силовых, кардио- и гибкостных тренировок. В комплекте чехол для переноски и краткое руководство.",
        "Протестировано профессиональными спортсменами и тренерами. Компактный дизайн экономит место, обеспечивая результаты профессионального уровня.",
        "Инвентарь соревновательного уровня, соответствующий международным стандартам. Усиленная конструкция выдерживает даже самые интенсивные нагрузки.",
        "Регулируемые настройки позволяют менять сопротивление по мере роста вашей подготовки. Отлично подходит для прогрессивной нагрузки.",
        "Дышащие влагоотводящие материалы сохраняют сухость при высокоинтенсивных интервалах. Надёжная посадка не сбивается при динамичных движениях.",
        "Всепогодный дизайн для тренировок на открытом воздухе круглый год. UV-стойкая поверхность легко очищается после каждого занятия.",
        "В комплекте иллюстрированное руководство по тренировкам и QR-код на бесплатные видеоуроки. Идеально для начинающих домашний спортзал.",
    ],
    "Дом и кухня": [
        "Кухонная принадлежность премиум-класса из пищевых материалов без BPA. Можно мыть в посудомоечной машине, создана для лёгкой ежедневной готовки.",
        "Прочная конструкция с элегантной отделкой, которая дополнит любой кухонный интерьер. Термостойкая и легко моется.",
        "Многофункциональный кухонный инструмент, экономящий время и место на столешнице. Интуитивное управление и стабильные результаты.",
        "Изготовлен из материалов ресторанного качества для превосходного распределения тепла и долговечности. Незаменимая вещь для ценителей домашней кулинарии.",
        "Компактный дизайн с вместительным объёмом для семейных порций. Энергоэффективная работа помогает снизить расходы на электричество.",
        "Антипригарное керамическое покрытие для здоровой готовки без масла. Подходит для духовки до 260 °C и всех типов плит, включая индукцию.",
        "Герметичная крышка сохраняет свежесть до пяти раз дольше обычных контейнеров. Штабелируемый дизайн поддерживает порядок в кладовой.",
        "Двойная вакуумная изоляция сохраняет температуру напитка на протяжении часов. Непроливаемая крышка и управление одной рукой — идеально в дороге.",
        "Точный контроль температуры с цифровым дисплеем для воспроизводимых результатов. Тихий мотор не помешает готовить рано утром или поздно вечером.",
        "Ручная работа из экологично заготовленного бамбука с пищевой минеральной пропиткой. Естественные антимикробные свойства и бережное отношение к ножам.",
    ],
    "Красота": [
        "Формула, протестированная дерматологами, с натуральными ингредиентами для бережного и эффективного ухода. Подходит для всех типов кожи, включая чувствительную.",
        "Люксовый продукт, питающий и восстанавливающий кожу с помощью клинически доказанных активных ингредиентов. Видимый результат через две недели регулярного применения.",
        "Профессиональный инструмент для красоты с салонным качеством результата в домашних условиях. Лёгкий эргономичный дизайн снижает усталость при длительном использовании.",
        "Безжестокостная формула без парабенов, обогащённая витаминами и антиоксидантами. Быстро впитывается, не оставляя жирного следа.",
        "Инновационное средство для ухода за кожей на основе научных исследований. Увлажняет, защищает и восстанавливает естественное сияние кожи.",
        "Веганская формула с экологично собранными ботаническими экстрактами. Стеклянная упаковка полностью перерабатывается.",
        "Термозащита до 230 °C, проверенная в салонах. Ионная технология уменьшает пушистость и придаёт зеркальный блеск за один проход.",
        "Наращиваемое покрытие, невесомое на коже. Обогащено гиалуроновой кислотой, чтобы поддерживать увлажнение под макияжем весь день.",
        "Ночной восстанавливающий комплекс с ретинолом и пептидами. Более упругая и гладкая кожа уже после одного применения перед сном.",
        "Стойкая формула сохраняет яркость до 12 часов без корректировки. Не переносится и не смазывается — уверенный цвет на весь день.",
    ],
    "Игрушки": [
        "Развивающая и увлекательная игрушка, которая стимулирует творчество и навыки решения задач. Изготовлена из нетоксичных безопасных материалов.",
        "Часы увлекательной игры для детей от 3 лет. Яркие цвета и прочная конструкция выдерживают даже самую активную игру.",
        "Отмеченная наградами игрушка для обучения STEM через практические эксперименты. В комплекте подробная инструкция и идеи проектов.",
        "Интерактивный игровой набор, который растёт вместе с ребёнком и предлагает несколько уровней сложности. Развивает мелкую моторику и пространственное мышление.",
        "Классическая игрушка в современном исполнении с улучшенными стандартами безопасности. Отличный подарок на день рождения для любознательных детей.",
        "Развлечение без экранов, увлекающее детей на часы. Развивает терпение, стратегию и социальные навыки через совместную игру.",
        "Экологичная игрушка из переработанного океанского пластика. Достаточно прочная для игр дома и на улице, при этом учит детей заботе об экологии.",
        "Расширяемая система, совместимая с крупнейшими брендами конструкторов. Начните с малого и пополняйте коллекцию тематическими наборами.",
        "Реалистичные звуковые эффекты и подсветка оживляют приключение. Рекомендуется для детей 5–12 лет. Батарейки в комплекте.",
        "Одобрена родителями и сертифицирована независимыми лабораториями. Закруглённые края, безвинцовая краска и моющаяся ткань для беззаботной игры.",
    ],
    "Продукты": [
        "Продукт премиум-качества с сертифицированных органических ферм. Богат натуральными питательными веществами, без искусственных консервантов и красителей.",
        "Вкусный и питательный перекус, идеальный для поддержания энергии в течение дня. Герметичная упаковка с застёжкой сохраняет свежесть.",
        "Тщательно отобранные ингредиенты, обработанные при строгом контроле качества. Отличный источник белка и клетчатки для сбалансированного питания.",
        "Продукт ремесленного производства с насыщенным, выразительным вкусом. Подходит для приготовления блюд, выпечки или употребления в чистом виде.",
        "Произведён с заботой об экологии в перерабатываемой упаковке. Низкое содержание сахара, богат витаминами и минералами для всей семьи.",
        "Обжарка малыми партиями для максимального аромата и глубины вкуса. Зёрна единого происхождения с прослеживаемостью до фермы.",
        "Без глютена, верифицировано как не-ГМО. Идеально для семей с аллергиями без компромиссов по вкусу и текстуре.",
        "Холодный отжим без рафинации для сохранения всех натуральных ферментов и нутриентов. Универсальный кулинарный продукт для заправок, маринадов и выпечки.",
        "Высокобелковый, низкоуглеводный перекус для кето- и палео-диет. Без добавленного сахара и подсластителей — только чистые, настоящие ингредиенты.",
        "Семейная упаковка с индивидуально завёрнутыми порциями для школьных обедов и путешествий. Сбалансированный сладко-солёный вкус нравится и детям, и взрослым.",
    ],
    "Автотовары": [
        "Универсальный автоаксессуар, совместимый с большинством марок и моделей автомобилей. Простая установка без инструментов менее чем за пять минут.",
        "Прочный автомобильный продукт, рассчитанный на экстремальные температуры и ежедневную эксплуатацию. Повышает комфорт вождения и организацию пространства в салоне.",
        "Автоаксессуар, ориентированный на безопасность, с надёжной работой в любых погодных условиях. Компактный дизайн не ограничивает обзор.",
        "Качественный автоаксессуар из премиальных материалов для долгосрочного использования. Улучшает впечатления от вождения и поддерживает порядок в автомобиле.",
        "Устройство plug-and-play с умными функциями для современных автомобилей. Энергоэффективная работа с защитой от перезаряда и короткого замыкания.",
        "Конструкция военного класса, испытанная на ударопрочность, вибрации и перепады температур. Идеально для внедорожников, пикапов и бездорожья.",
        "Качество OEM-замены, соответствующее заводским спецификациям. Восстанавливает характеристики и проходит техосмотр без модификаций.",
        "Крепление с поворотом на 360° и механизмом фиксации одним касанием. Виброгасящая подкладка защищает телефон от дорожной тряски.",
        "Ультраяркие LED с ресурсом 50 000 часов. Мгновенное включение, без прогрева, сфокусированный луч не слепит встречный транспорт.",
        "Отделка из экокожи с подушкой из пены с памятью для комфорта в дальних поездках. Подходит для большинства передних и задних сидений.",
    ],
    "Сад и огород": [
        "Прочный садовый инструмент для профессиональных ландшафтных дизайнеров и домашних садоводов. Антикоррозийное покрытие обеспечивает долгие сезоны надёжной работы.",
        "Экологичное решение для садоводства, способствующее здоровью почвы и активному росту растений. Лёгкая сборка без специальных инструментов.",
        "Атмосферостойкий продукт для открытого воздуха, устойчивый к солнцу, дождю и морозу. Привлекательный дизайн украсит любой двор или террасу.",
        "Эргономичный садовый инструмент, снижающий нагрузку на руки и спину при длительной работе в саду. Лёгкий, но достаточно прочный для тяжёлых задач.",
        "Полный набор для садоводства со всем необходимым для немедленного начала посадки. Идеален для высоких грядок, контейнерного садоводства и ландшафтных проектов.",
        "Система автополива поддерживает увлажнение растений до двух недель. Отлично подходит для отпусков и загруженного графика.",
        "Рама из оцинкованной стали выдерживает годы на открытом воздухе без ржавчины. Быстросъёмные соединения упрощают сезонную сборку.",
        "На солнечных батареях с автоматическим датчиком сумерки-рассвет. Без проводки — просто воткните в землю и наслаждайтесь тёплым рассеянным светом.",
        "Расширяемая модульная конструкция позволяет настраивать планировку под любую форму сада. Легко перестраивается по мере развития посадочного плана.",
        "Органическая формула, одобренная для пищевых садов. Стимулирует полезные микроорганизмы и естественным образом подавляет типичных садовых вредителей.",
    ],
}


def generate_catalog():
    rng = random.Random(SEED)
    products = []

    for i in range(1, HALF + 1):
        cat_idx = (i - 1) % len(CATEGORIES_RU)
        cat_ru = CATEGORIES_RU[cat_idx]
        name_tpl = rng.choice(NAMES_RU[cat_ru])
        modifier = rng.choice(BOOK_TOPICS_RU) if cat_ru == "Книги" else rng.choice(BRANDS_RU)
        products.append({
            "id": i,
            "name": name_tpl.format(modifier),
            "category": cat_ru,
            "description": rng.choice(DESCS_RU[cat_ru]),
            "lang": "ru",
        })

    for i in range(HALF + 1, TOTAL + 1):
        cat_idx = (i - HALF - 1) % len(CATEGORIES_EN)
        cat_en = CATEGORIES_EN[cat_idx]
        name_tpl = rng.choice(NAMES_EN[cat_en])
        modifier = rng.choice(BOOK_TOPICS_EN) if cat_en == "Books" else rng.choice(BRANDS_EN)
        products.append({
            "id": i,
            "name": name_tpl.format(modifier),
            "category": cat_en,
            "description": rng.choice(DESCS_EN[cat_en]),
            "lang": "en",
        })

    return products


def main():
    catalog = generate_catalog()

    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "catalog_seed.json")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)

    ru_count = sum(1 for p in catalog if p["lang"] == "ru")
    en_count = sum(1 for p in catalog if p["lang"] == "en")
    cats = sorted(set(p["category"] for p in catalog))

    print(f"Generated {len(catalog)} products -> {out_path}")
    print(f"  Russian: {ru_count}, English: {en_count}")
    print(f"  Categories ({len(cats)}): {', '.join(cats)}")


if __name__ == "__main__":
    main()
